channel_secret: 'b785284b67c9d36976edf52b6eab2965'
channel_access_token: '4dzmR60neA5KGaXUm2bo5TqodEx3Blm6QO2NXW1H1XICpfmIcKavMN28V57Uifqro2uuZtkJ0F3O0mKB6V3RU5ywzBNaSV4sy4H0QRr0MrJ7yBBX23O7/U6gVCDm1rwwmQItMKyK3Qvm2rUobtah+AdB04t89/1O/w1cDnyilFU='
admin: 'U7f0a352e06e2b7146a0d53a5f16e516d'
flex_grade:
  type: bubble
  hero:
    type: image
    url: https://arc.blossom-academy.uk/static/c-grade.jpg
    size: full
    aspectRatio: '4:3'
    aspectMode: cover
  body:
    type: box
    layout: vertical
    backgroundColor: '#1a2a4a'
    paddingAll: 20px
    contents:
    - type: text
      text: Blossom Academy
      color: '#a1b5cc'
      size: sm
      weight: bold
      align: center
    - type: button
      action:
        type: uri
        label: 評分結果...
        uri: $LIFF_URL$
      style: primary
      color: '#2c4a7c'
      margin: xl
      height: sm

flex_welcome:
  type: bubble
  hero:
    type: image
    url: https://arc.blossom-academy.uk/static/c-welcome.jpg
    size: full
    aspectRatio: '4:3'
    aspectMode: cover
  body:
    type: box
    layout: vertical
    backgroundColor: '#1a2a4a'
    paddingAll: 20px
    contents:
    - type: text
      text: Blossom Academy
      color: '#a1b5cc'
      size: sm
      weight: bold
      align: center
    - type: button
      style: primary
      color: '#2c4a7c'
      margin: xl
      height: sm
      action:
        type: postback
        label: 輸入驗證碼
        data: hello

flex_upload:
  type: bubble
  hero:
    type: image
    url: https://arc.blossom-academy.uk/static/c-upload.jpg
    size: full
    aspectRatio: '4:3'
    aspectMode: cover
  body:
    type: box
    layout: vertical
    backgroundColor: '#1a2a4a'
    paddingAll: 20px
    contents:
    - type: text
      text: Blossom Academy
      color: '#a1b5cc'
      size: sm
      weight: bold
      align: center
    - type: button
      action:
        type: postback
        label: 請上傳圖片
        data: action=upload_file
      style: primary
      color: '#2c4a7c'
      margin: xl
      height: sm

